### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by Brad2024** [Stilic/Forever-Modding#5]
The accuracy kept on saying 50%, giving an F.

**Comment by Stilic** [comment]
fixed by removing skipCalculations shit

**Comment by Brad2024** [comment]
How do I remove skipCalculations?

**Comment by Stilic** [comment]
> How do I remove skipCalculations?

it is already removed.

**Comment by Stilic** [comment]
> Did you remove it from the buildWindows version?

removed it from all builds bruh
