### ISSUE TITLE
Accuracy is way harsher than it should be, even during SFCs

### ISSUE THREAD

**Issue by BeastlyGhost** [Stilic/Forever-Modding#8]
It's basically impossible to get S+ because accuracy starts at 70% for SFCs for whatever reason
I'd probably fix this by making it so it checks if allSicks is enabled on PlayState, if it is, then accuracy should spike to 100%, then if it's not allSicks, it should decrease the accuracy according to which rating you got (ex: Good should decrease it to 99,03% or something similar)

https://user-images.githubusercontent.com/45212377/158832731-d60feff3-c1a8-475d-b80a-9001297a251a.mp4

it shouldn't be *this* harsh, but it is

**Comment by Stilic** [comment]
yes can you fix that?

**Comment by BeastlyGhost** [comment]
fixed, will PR soon!
